### PR TITLE
Objects can now be grabbed by the pointer from the left touch controller

### PR DESCRIPTION
**Pull request by njbrown**

### CODE REVIEW

**Comment by njbrown** [comment]
Fixed the author issue by squashing the comits, but the build breaks because the controller models are missing :(
We'll have to merge this on thursday

**Comment by njbrown** [comment]
Turns out that the assets were in there, i just needed to delete the build output folder. Just cleaning the build from inside the editor isnt enough.

**Comment by njbrown** [comment]
@iKlsR test and merge please

**Comment by iKlsR** [comment]
Looks good. LGTM 🐸

**Pull request merged**
